### ISSUE TITLE
Q&A: Meta programming in Java

### ISSUE THREAD

**Issue by hientt1911** [hientt1911/pageobject-junit-webdriver#15]
`@FindBy(xpath="//div[@id='body_type_ids']/div/label")
	WebElementFacade randomBody;
	
	@FindBy(xpath="//div[@id='body_type_ids']/div[2]/label")
	WebElementFacade thin;
	
	@FindBy(xpath="//div[@id='body_type_ids']/div[3]/label")
	WebElementFacade medium;
	
	@FindBy(xpath="//div[@id='body_type_ids']/div[4]/label")
	WebElementFacade sport;
	
	@FindBy(xpath="//div[@id='body_type_ids']/div[5]/label")
	WebElementFacade strong;
	
	@FindBy(xpath="//div[@id='body_type_ids']/div[6]/label")
	WebElementFacade fat;
	
	@FindBy(xpath="//div[@id='body_type_ids']/div[7]/label")
	WebElementFacade big;
	
	@FindBy(xpath="//div[@id='body_type_ids']/div[8]/label")
	WebElementFacade tall;`

How can I write  shorter?

**Comment by Jacobvu84** [comment]
@hientt1911 Good question

**Comment by Jacobvu84** [comment]
[xpath_axes](https://www.tutorialspoint.com/xpath/xpath_axes.htm)
